#!/usr/bin/env bash
set -e
cd "$(git rev-parse --show-toplevel)"
bin/ap ./vendor/bin/pint --test
bin/ap ./vendor/bin/phpstan analyse --memory-limit=1G --no-progress
bin/ap ./vendor/bin/pest --parallel --stop-on-failure
